services:
  app:
    build: .
    container_name: webhook-bot
    ports:
      - "8080:8080"
    environment:
      - API_TOKEN=${API_TOKEN}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
    - C:/Users/Kennys/Desktop/school21/teleAPI/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  db_data: {}
