
services:
  app:
    build: .
    container_name: webhook-bot
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=${API_TOKEN}
    volumes:
      - .:/app  
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
